apiVersion: v1
kind: Service
metadata:
  name: app-one-service
spec:
  selector:
    app: app-one
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
    - port: 5432
      targetPort: 5432
      nodePort: 30002
  type: NodePort
