apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one-container
          image: appone:latest
          ports:
            - containerPort: 8081