apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - name: app-two-container
          image: docker.io/library/apptwo:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8082