apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one-container
          image: appone:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 5005
          env:
            - name: "JAVA_OPTS"
              value: "- agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"